"""Check commit_lint against messages that must be flagged and messages that must pass.

    python tests/test_commit_lint.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tools"))
from commit_lint import DEFAULTS, lint, verdict  # noqa: E402


def d(*files, lines=30):
    return {"files": list(files), "lines": lines}


# (name, message, diff, author, expected verdict: "block", "flag" (warn or block), or "ok")
CASES = [
    # ---- hard tier ----
    ("claude code default", "Add retry logic to the fetcher\n\n\U0001F916 Generated with [Claude Code](https://claude.com/claude-code)\n\n"
     "Co-Authored-By: Claude <noreply@anthropic.com>", d("fetch.py"), "", "block"),
    ("claude model co-author", "fix: handle empty feed\n\nCo-Authored-By: Claude Opus 4.5 <noreply@anthropic.com>", d("feed.js"), "", "block"),
    ("copilot co-author", "Fix login redirect\n\nCo-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>", d("login.ts"), "", "block"),
    ("assisted-by trailer", "Speed up the parser\n\nAssisted-by: Claude", d("parse.py"), "", "block"),
    ("signed-off-by an ai", "Tidy imports\n\nSigned-off-by: Claude <claude@anthropic.com>", d("a.py"), "", "block"),
    ("replit agent trailers", "Add product grid\n\nReplit-Commit-Author: Agent\nReplit-Commit-Session-Id: b103ecc2", d("index.html"), "", "block"),
    ("robot emoji alone", "Bump deps \U0001F916", d("package.json"), "", "block"),
    ("generated by chatgpt", "Add CSV export\n\nGenerated by ChatGPT", d("export.py"), "", "block"),
    ("aider author", "Add caching", d("cache.py"), "Paul Gauthier (aider) <paul@example.com>", "block"),
    ("devin bot author", "Update deps", d("package.json"), "devin-ai-integration[bot] <158243242+devin-ai-integration[bot]@users.noreply.github.com>", "block"),

    # ---- scored tier ----
    ("gitmoji and mirrored bullets", "✨ feat(auth): add OAuth2 login support\n\n- Add OAuth2 provider configuration\n"
     "- Update login page with OAuth buttons\n- Add token refresh handling\n- Update documentation",
     d("auth/config.py", "templates/login.html", "auth/tokens.py", "README.md", lines=120), "", "flag"),
    ("this commit enhances", "Refactor user service\n\nThis commit refactors the UserService class to improve code quality and "
     "maintainability. It streamlines the validation logic and ensures consistent handling across various methods. "
     "Overall, these changes make the codebase more robust.", d("user_service.py", lines=40), "", "flag"),
    ("markdown pr template body", "Update API client\n\n## Summary\n\nThis PR updates the client.\n\n## Changes\n\n"
     "- **Added** retry\n- **Updated** timeout", d("client.py", lines=25), "", "flag"),
    ("performative casual", "lol finally fix the thing where retries double-count\n\nmoved the counter increment out of the retry "
     "loop, added a guard in send_request(), and updated test_retry.py, retry.py, client.py to match",
     d("retry.py", "client.py", "test_retry.py", lines=30), "", "flag"),
    ("claims tests with none", "Add input validation with unit tests", d("validate.py", lines=20), "", "flag"),
    ("long body tiny diff", "Update retry count\n\nUpdated the default retry count in the configuration.\n"
     "The previous value has been replaced with a new value.\nThis keeps the configuration aligned.\n"
     "The change is small and contained.\nNo other settings are affected.\nThe new value applies everywhere.\n"
     "Documentation remains accurate.", d("config.py", lines=2), "", "flag"),
    ("labeled sections", "Add health endpoint\n\nSummary:\nAdds a health endpoint for the API.\n\nChanges:\n"
     "- Added /health route\n- Added response model\n- Updated router registration\n\nTesting:\nManual.",
     d("api/health.py", "api/models.py", "api/router.py", lines=45), "", "flag"),

    # ---- must pass: human styles ----
    ("bellard lowercase past", "fixed memory leak in Atomics.store (#537)", d("quickjs.c", lines=6), "", "ok"),
    ("bellard bare", "added JS_NewSymbol()", d("quickjs.c", "quickjs.h", lines=40), "", "ok"),
    ("bellard update", "test262 update", d("test262.conf", lines=300), "", "ok"),
    ("antirez period", "redis-cli: fix #5096 double error message.", d("src/redis-cli.c", lines=8), "", "ok"),
    ("kernel style", "mm/slub: fix use-after-free in kmem_cache_destroy\n\nWhen a cache is destroyed while a deferred free is "
     "still queued, the\nworker dereferences the freed cache. syzbot hit this, and it reproduces\nin about 30s under "
     "a stress loop.\n\nFlush the deferred work before tearing down the cache.\n\n"
     "Fixes: 1a2b3c4d5e6f (\"mm/slub: defer frees\")\nReported-by: syzbot+abc@syzkaller.appspotmail.com\n"
     "Signed-off-by: Jane Dev <jane@example.org>", d("mm/slub.c", lines=14), "", "ok"),
    ("typo", "typo", d("README.md", lines=2), "", "ok"),
    ("revert with reason", "revert the retry cap because it hid real timeouts", d("retry.py", lines=10), "", "ok"),
    ("git revert", "Revert \"add cache\"\n\nThis reverts commit abc1234def.", d("cache.py", lines=50), "", "ok"),
    ("bump", "bump version", d("package.json", lines=2), "", "ok"),
    ("about an llm feature", "Add a Claude API timeout to the summarizer\n\nThe Workers AI call sometimes hangs past the 30s "
     "CPU limit, so the\nClaude fallback never ran. Cap it at 10s and fall through.", d("src/summarize.js", lines=12), "", "ok"),
    ("llm prose mentions generated", "Strip code fences from summaries\n\nGenerated by Claude, the summaries sometimes wrap "
     "JSON in code fences,\nwhich broke the parser.", d("src/summarize.js", lines=9), "", "ok"),
    ("mcp hook commit", "Raise the MCP server timeout for the Claude Code hook\n\nThe hook timed out on cold starts.",
     d("hook/settings.json", lines=2), "", "ok"),
    ("conventional with why", "fix: stop the backfill from starting over after a crash\n\nProgress was only saved at the end, "
     "so a tab crash lost hours of scrolling.\nSave it after each page instead.", d("background.js", lines=25), "", "ok"),
    ("first person hedge", "Try a smaller batch size\n\nI'm not sure this is right, but 50 stops the 429s I kept hitting.",
     d("sync.py", lines=3), "", "ok"),
    ("human co-author", "Fix date parsing\n\nCo-authored-by: Kai Smith <kai@example.com>", d("dates.py", lines=8), "", "ok"),
    ("mundane two-file subject", "Add Tuning Tips nav button to calculator header, lift shared nav-link styles to style.css",
     d("index.html", "style.css", lines=40), "", "ok"),
    ("merge", "Merge branch 'main' into feature", None, "", "ok"),
]

failures = []
for name, msg, diff, author, want in CASES:
    hard, score, scored = lint(msg, diff, author, DEFAULTS)
    got = verdict(hard, score, DEFAULTS)
    ok = got == want or (want == "flag" and got in ("warn", "block"))
    if not ok:
        rules = [f[0] for f in hard] + [f"{f[0]}{f[1]:+d}" for f in scored]
        failures.append(f"{name}: want {want}, got {got} (score {score}) {rules}")

if failures:
    print("commit_lint: misclassified\n  " + "\n  ".join(failures))
    sys.exit(1)
print(f"commit_lint: all {len(CASES)} cases classified")
